Compra de Snacks
rodrigotrelles/isa2-obligatorio pull request #57
Opened 2023-05-07 20:38 UTC by rodrigotrelles

2023-05-08 02:00 UTC, fedper95 requested changes
Tremendo! Dejé unos comentarios para mantener código en inglés pero más allá de eso LGTM

2023-05-10 01:56 UTC, rodrigotrelles commented on Obligatorio/codigo/ArenaGestor/ArenaGestor.API/appsettings.json
> +    "ArenaGestorContext": "Server=.\\;Database=ArenaGestorDB;Trusted_Connection=True;MultipleActiveResultSets=True;"
si

2023-05-10 01:58 UTC, rodrigotrelles commented on Obligatorio/codigo/ArenaGestorFront/src/app/routes/buy/buy.component.html
> +                (change)="RecalcularSubtotal()">
listo!

2023-05-10 01:58 UTC, rodrigotrelles commented on Obligatorio/codigo/ArenaGestorFront/src/app/routes/snacks/snack-form.component.html
> +        <button class="btn btn-primary btn-small" (click)="Confirmar()">Confirmar</button>
listo

2023-05-10 01:59 UTC, rodrigotrelles commented on Obligatorio/codigo/ArenaGestorFront/src/app/routes/buy/buy.component.ts
> +    console.log('hiii')
listo

2023-05-10 02:07 UTC, merged